events {
    worker_connections 1024;
}

http {
    upstream gateways {
        server gateway-1:8080;
        server gateway-2:8080;
        server gateway-3:8080;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://gateways;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}