spring.application.name=Distributed-Rate-Limiter
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379} 
resilience4j.circuitbreaker.instances.downstream-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.downstream-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.downstream-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.downstream-service.permitted-number-of-calls-in-half-open-state=3   
